---
title: "TCGA-Nigerian-RNASeq Project"

site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    df_print: paged
    toc: true
    theme: spacelab
    highlight: textmate
---

Padma Sheila Rajagopal, MD MPH
Olopade Lab / Im Lab Postdoctoral Fellow

This is the site I will use for reporting on projects in which I am assessing differential expression between initial tumor samples from Nigerian women with breast cancer and initial tumor samples from TCGA breast samples. 

Workflow as below:

#Protocols

* *Alignment*: STAR (completed prior to analysis by Dominic Fitzgerald), initial steps of 
[PsychENCODE pipeline]: (https://gist.github.com/djf604/a3d6925c3775d6cf1053ded0e7a8b148)

* *Raw read counts*: HTSeq (completed prior to analysis by Dominic Fitzgerald)

* *Differential expression*: Limma-voom w/ quantile normalization for direct comparison

* *Differential expression (Nigerian only)*: DESeq2

Analysis as below:

#Differential expression:

* Batch effect correction exploration: 
https://parajago.github.io/TCGA-Nigerian-RNAseq/NigerianTCGArawcountsDeSeq2-pc2.html

* Differential expression analysis (protein coding genes only) comparing directly TCGA and Nigerian samples: https://parajago.github.io/TCGA-Nigerian-RNAseq/NigerianTCGArawcountslimma-voomDE-PAM50.html

* Differential expression analysis (protein coding genes only) using samples with whole genome sequencing available as part of an accompanying project to the Life History Analysis: https://parajago.github.io/TCGA-Nigerian-RNAseq/NigerianTCGArawcountsDeSeq2-proteincoding-IHC.html

* Differential expression analysis of long noncoding RNA comparing directly between TCGA and Nigerian samples: https://parajago.github.io/TCGA-Nigerian-RNAseq/NigerianTCGA-lnc.html